name: live_app
description: 虎牙液态玻璃直播客户端
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  live_core:
    path: ../live_core
  get: ^4.6.6
  video_player: ^2.14.0
  liquid_glass_widgets: ^0.30.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
